[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm install"  # This ensures @google/generative-ai is installed

[[plugins]]
  package = "@netlify/plugin-functions-install-core"  # Ensures functions get bundled properly
